#!/usr/bin/env python3.8

import requests
import gender_guesser.detector as gender
from argparse import ArgumentParser


parser = ArgumentParser(description='Get the names of the members of a meetup group')
parser.add_argument('group', help='Name of the group, as it appears in the URL of the platform')

args = parser.parse_args()

url = f"https://api.meetup.com/{args.group}/members?&sign=true&photo-host=public&page=10000&only=name"

res = requests.get(url)

if res.status_code != 200:
    print(f"Error fetch data: {res.status_code}")
    sys.exit(1)

print(f"The request has returned {len(res.json())} results")

detector = gender.Detector()

women = []

for json in res.json():
    fullname = json['name']
    name = fullname.split()[0]
    gender = detector.get_gender(name, u'spain')

    if gender not in ["male", "unknown", "andy"]:
        women.append(fullname)
        print(fullname)

print(f"In the meetup group {args.group} might be {len(women)} women")

